via_options: {
  address:               'smtp.gmail.com',
  port:                  '587',
  user_name:             'gmail@gmail.com'
  password:              'password_password'
  authentication:        :plain, # :plain, :login, :cram_md5, no auth by default
  enable_starttls_auto:  true,
}
